### ISSUE TITLE
I'm getting error

### ISSUE THREAD

**Issue by Jaykumaran** [marvik-ai/llama2-nemo-guardrails#1]
![Screenshot 2023-12-28 184757](https://github.com/marvik-ai/llama2-nemo-guardrails/assets/60032500/938c428d-3225-4ead-ad6b-a6ab8f80ee27)

I exactly cloned you rrepo and run in colab ,i'm getting _acall error.Help me out with this

**Comment by Jaykumaran** [comment]
!pip install nemoguardrails   openai transformers langchain -Uqqqq

import huggingface_hub
huggingface_hub.login(token=os.environ["HUGGINGFACEHUB_API_TOKEN"])


from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from langchain.llms import HuggingFacePipeline

## Load hugging face credentials
import huggingface_hub
huggingface_hub.login(token=os.environ["HUGGINGFACEHUB_API_TOKEN"])

## Load model and tokenizer
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from langchain.llms import HuggingFacePipeline

MODEL_NAME = "meta-llama/Llama-2-7b-chat-hf"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,            # load model in 4-bit precision
    bnb_4bit_quant_type="nf4",    # pre-trained model should be quantized in 4-bit NF format
    bnb_4bit_use_double_quant=True, # Using double quantization as mentioned in QLoRA paper
    bnb_4bit_compute_dtype=torch.bfloat16,
    # During computation, pre-trained model should be loaded in BF16 format
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    # quantization_config = bnb_config,
    device_map = 'auto',
    # use_cache=True,
    # trust_remote_code=True,

)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)



pipe = pipeline(
    "text-generation",
    model=model, 
    tokenizer=tokenizer,
    max_length=4096,
    do_sample=True,
    temperature=0.2,
    top_p=0.95,
    logprobs=None,
    top_k=40,
    repetition_penalty=1.1
)

llm = HuggingFacePipeline(pipeline=pipe)

**Comment by omkargadute** [comment]
Facing the same issue.

**Comment by Jaykumaran** [comment]
,Thanks i found reason for my error,I was using HuggingFacePipeline from langchain instead of HuggingFacePipelineCompatible from nemoguardrails..

I hereby attach steps i followed with @Wildshire guidance to successfully work it out.

https://github.com/Jaykumaran/Guardrails/blob/main/NemoGuardrails/Nemoguardrails_Llama_Git_Issue.ipynb

To add on,I think config.py is a excellent code base to check out whats going error.I fixes my error by comparing the function and lib callings from

 https://github.com/NVIDIA/NeMo-Guardrails/blob/develop/examples/configs/llm/hf_pipeline_llama2/config.py
